[build-system]
requires = ["setuptools", "wheel", "cython>=3", "oldest-supported-numpy"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:FilePath is supplanted",
    "ignore:is_valid is not useful",
    "ignore:The given matrix is",
    "ignore:Dataset has no geotransform",
]
markers = [
    "slow: marks tests as slow",
    "gdalbin: marks test requiring GDAL binaries",
    "wheel: marks test specific to wheel-building infra",
    "network: marks tests that require network access"
]
