name: CI using GDAL ubuntu-small-333
on: [push]
jobs:
  "run-tests-in-container":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: GDAL=ubuntu-small-333 make dockertest
