name: CI

# On every pull request, but only on push to master
on:
  push:
    branches:
    - master
    - maint*
    tags:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    container: osgeo/gdal:ubuntu-full-${{ matrix.gdal-version }}
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        gdal-version: ['3.4.0', '3.3.3', '3.2.3', '3.1.3', '3.0.4']

    steps:
      - uses: actions/checkout@v2

      - name: update
        run: |
          apt-get update -y
          apt-get install build-essential nodejs -y

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip wheel -r requirements-dev.txt
          python -m pip install -r requirements-dev.txt
          python setup.py clean
          python -m pip install --no-deps --force-reinstall --no-use-pep517 -e .[test]

      - name: run tests
        run: python -m pytest -v -m "not wheel" -rxXs --cov rasterio --cov-report term-missing

